version: '3.8'
services:
  redis_container:
    image: redis:latest
    container_name: tenverse-redis
    ports:
      - 6379:6379

    volumes:
      - ./redis/data:/data
      - ../redis/redis.conf:/user/local/conf/redis.conf

    labels:
      - "name=redis"
      - "mode=standalone"

    restart: always
    command: redis-server /user/local/conf/redis.conf